# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mlmvn_gui.ui'
#
# Created: Fri Sep 18 12:35:24 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1145, 753)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.group_io = QtGui.QGroupBox(self.centralwidget)
        self.group_io.setObjectName("group_io")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.group_io)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.layout_samples = QtGui.QHBoxLayout()
        self.layout_samples.setObjectName("layout_samples")
        self.label = QtGui.QLabel(self.group_io)
        self.label.setObjectName("label")
        self.layout_samples.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_samples.addItem(spacerItem)
        self.field_samples = QtGui.QLineEdit(self.group_io)
        self.field_samples.setObjectName("field_samples")
        self.layout_samples.addWidget(self.field_samples)
        self.button_importSamples = QtGui.QToolButton(self.group_io)
        self.button_importSamples.setObjectName("button_importSamples")
        self.layout_samples.addWidget(self.button_importSamples)
        self.verticalLayout_14.addLayout(self.layout_samples)
        self.layout_topology = QtGui.QHBoxLayout()
        self.layout_topology.setObjectName("layout_topology")
        self.label_2 = QtGui.QLabel(self.group_io)
        self.label_2.setObjectName("label_2")
        self.layout_topology.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.layout_topology.addItem(spacerItem1)
        self.field_topology = QtGui.QLineEdit(self.group_io)
        self.field_topology.setObjectName("field_topology")
        self.layout_topology.addWidget(self.field_topology)
        spacerItem2 = QtGui.QSpacerItem(26, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_topology.addItem(spacerItem2)
        self.verticalLayout_14.addLayout(self.layout_topology)
        self.layout_properties = QtGui.QHBoxLayout()
        self.layout_properties.setObjectName("layout_properties")
        self.label_3 = QtGui.QLabel(self.group_io)
        self.label_3.setObjectName("label_3")
        self.layout_properties.addWidget(self.label_3)
        self.box_sectors = QtGui.QSpinBox(self.group_io)
        self.box_sectors.setObjectName("box_sectors")
        self.layout_properties.addWidget(self.box_sectors)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_properties.addItem(spacerItem3)
        self.check_discreteIn = QtGui.QCheckBox(self.group_io)
        self.check_discreteIn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check_discreteIn.setObjectName("check_discreteIn")
        self.layout_properties.addWidget(self.check_discreteIn)
        self.check_discreteOut = QtGui.QCheckBox(self.group_io)
        self.check_discreteOut.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check_discreteOut.setObjectName("check_discreteOut")
        self.layout_properties.addWidget(self.check_discreteOut)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_properties.addItem(spacerItem4)
        self.verticalLayout_14.addLayout(self.layout_properties)
        self.gridLayout.addWidget(self.group_io, 0, 0, 1, 1)
        self.group_error = QtGui.QGroupBox(self.centralwidget)
        self.group_error.setObjectName("group_error")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.group_error)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layout_stopKeySelect = QtGui.QHBoxLayout()
        self.layout_stopKeySelect.setObjectName("layout_stopKeySelect")
        self.label_stopKey = QtGui.QLabel(self.group_error)
        self.label_stopKey.setObjectName("label_stopKey")
        self.layout_stopKeySelect.addWidget(self.label_stopKey)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_stopKeySelect.addItem(spacerItem5)
        self.combo_stopKey = QtGui.QComboBox(self.group_error)
        self.combo_stopKey.setObjectName("combo_stopKey")
        self.combo_stopKey.addItem("")
        self.combo_stopKey.addItem("")
        self.combo_stopKey.addItem("")
        self.combo_stopKey.addItem("")
        self.combo_stopKey.addItem("")
        self.layout_stopKeySelect.addWidget(self.combo_stopKey)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_stopKeySelect.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.layout_stopKeySelect)
        self.stacked_stopKey = QtGui.QStackedWidget(self.group_error)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stacked_stopKey.sizePolicy().hasHeightForWidth())
        self.stacked_stopKey.setSizePolicy(sizePolicy)
        self.stacked_stopKey.setObjectName("stacked_stopKey")
        self.maxError = QtGui.QWidget()
        self.maxError.setObjectName("maxError")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.maxError)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layout_maxGlobal = QtGui.QHBoxLayout()
        self.layout_maxGlobal.setObjectName("layout_maxGlobal")
        self.label_10 = QtGui.QLabel(self.maxError)
        self.label_10.setObjectName("label_10")
        self.layout_maxGlobal.addWidget(self.label_10)
        spacerItem7 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_maxGlobal.addItem(spacerItem7)
        self.box_maxGlobal = QtGui.QSpinBox(self.maxError)
        self.box_maxGlobal.setObjectName("box_maxGlobal")
        self.layout_maxGlobal.addWidget(self.box_maxGlobal)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_maxGlobal.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.layout_maxGlobal)
        self.layout_maxLocal = QtGui.QHBoxLayout()
        self.layout_maxLocal.setObjectName("layout_maxLocal")
        self.label_11 = QtGui.QLabel(self.maxError)
        self.label_11.setObjectName("label_11")
        self.layout_maxLocal.addWidget(self.label_11)
        spacerItem9 = QtGui.QSpacerItem(29, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_maxLocal.addItem(spacerItem9)
        self.box_maxLocal = QtGui.QSpinBox(self.maxError)
        self.box_maxLocal.setObjectName("box_maxLocal")
        self.layout_maxLocal.addWidget(self.box_maxLocal)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_maxLocal.addItem(spacerItem10)
        self.verticalLayout_5.addLayout(self.layout_maxLocal)
        self.stacked_stopKey.addWidget(self.maxError)
        self.errorRate = QtGui.QWidget()
        self.errorRate.setObjectName("errorRate")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.errorRate)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.layout_errorGlobal = QtGui.QHBoxLayout()
        self.layout_errorGlobal.setObjectName("layout_errorGlobal")
        self.label_12 = QtGui.QLabel(self.errorRate)
        self.label_12.setObjectName("label_12")
        self.layout_errorGlobal.addWidget(self.label_12)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_errorGlobal.addItem(spacerItem11)
        self.box_errorGlobal = QtGui.QDoubleSpinBox(self.errorRate)
        self.box_errorGlobal.setSuffix("")
        self.box_errorGlobal.setObjectName("box_errorGlobal")
        self.layout_errorGlobal.addWidget(self.box_errorGlobal)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_errorGlobal.addItem(spacerItem12)
        self.verticalLayout_7.addLayout(self.layout_errorGlobal)
        self.layout_errorLocal = QtGui.QHBoxLayout()
        self.layout_errorLocal.setObjectName("layout_errorLocal")
        self.label_13 = QtGui.QLabel(self.errorRate)
        self.label_13.setObjectName("label_13")
        self.layout_errorLocal.addWidget(self.label_13)
        spacerItem13 = QtGui.QSpacerItem(55, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_errorLocal.addItem(spacerItem13)
        self.box_errorLocal = QtGui.QSpinBox(self.errorRate)
        self.box_errorLocal.setObjectName("box_errorLocal")
        self.layout_errorLocal.addWidget(self.box_errorLocal)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_errorLocal.addItem(spacerItem14)
        self.verticalLayout_7.addLayout(self.layout_errorLocal)
        self.stacked_stopKey.addWidget(self.errorRate)
        self.mse = QtGui.QWidget()
        self.mse.setObjectName("mse")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.mse)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.layout_mseGlobal = QtGui.QHBoxLayout()
        self.layout_mseGlobal.setObjectName("layout_mseGlobal")
        self.label_14 = QtGui.QLabel(self.mse)
        self.label_14.setObjectName("label_14")
        self.layout_mseGlobal.addWidget(self.label_14)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_mseGlobal.addItem(spacerItem15)
        self.box_mseGlobal = QtGui.QDoubleSpinBox(self.mse)
        self.box_mseGlobal.setObjectName("box_mseGlobal")
        self.layout_mseGlobal.addWidget(self.box_mseGlobal)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_mseGlobal.addItem(spacerItem16)
        self.verticalLayout_8.addLayout(self.layout_mseGlobal)
        self.layout_mseLocal = QtGui.QHBoxLayout()
        self.layout_mseLocal.setObjectName("layout_mseLocal")
        self.label_15 = QtGui.QLabel(self.mse)
        self.label_15.setObjectName("label_15")
        self.layout_mseLocal.addWidget(self.label_15)
        spacerItem17 = QtGui.QSpacerItem(47, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_mseLocal.addItem(spacerItem17)
        self.box_mseLocal = QtGui.QDoubleSpinBox(self.mse)
        self.box_mseLocal.setObjectName("box_mseLocal")
        self.layout_mseLocal.addWidget(self.box_mseLocal)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_mseLocal.addItem(spacerItem18)
        self.verticalLayout_8.addLayout(self.layout_mseLocal)
        self.stacked_stopKey.addWidget(self.mse)
        self.rmse = QtGui.QWidget()
        self.rmse.setObjectName("rmse")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.rmse)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layout_rmseGlobal = QtGui.QHBoxLayout()
        self.layout_rmseGlobal.setObjectName("layout_rmseGlobal")
        self.label_17 = QtGui.QLabel(self.rmse)
        self.label_17.setObjectName("label_17")
        self.layout_rmseGlobal.addWidget(self.label_17)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_rmseGlobal.addItem(spacerItem19)
        self.box_rmseGlobal = QtGui.QDoubleSpinBox(self.rmse)
        self.box_rmseGlobal.setObjectName("box_rmseGlobal")
        self.layout_rmseGlobal.addWidget(self.box_rmseGlobal)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_rmseGlobal.addItem(spacerItem20)
        self.verticalLayout_4.addLayout(self.layout_rmseGlobal)
        self.layout_rmseLocal = QtGui.QHBoxLayout()
        self.layout_rmseLocal.setObjectName("layout_rmseLocal")
        self.label_16 = QtGui.QLabel(self.rmse)
        self.label_16.setObjectName("label_16")
        self.layout_rmseLocal.addWidget(self.label_16)
        spacerItem21 = QtGui.QSpacerItem(47, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_rmseLocal.addItem(spacerItem21)
        self.box_rmseLocal = QtGui.QDoubleSpinBox(self.rmse)
        self.box_rmseLocal.setObjectName("box_rmseLocal")
        self.layout_rmseLocal.addWidget(self.box_rmseLocal)
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_rmseLocal.addItem(spacerItem22)
        self.verticalLayout_4.addLayout(self.layout_rmseLocal)
        self.stacked_stopKey.addWidget(self.rmse)
        self.armse = QtGui.QWidget()
        self.armse.setObjectName("armse")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.armse)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.layout_armseGlobal = QtGui.QHBoxLayout()
        self.layout_armseGlobal.setObjectName("layout_armseGlobal")
        self.label_8 = QtGui.QLabel(self.armse)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.layout_armseGlobal.addWidget(self.label_8)
        spacerItem23 = QtGui.QSpacerItem(24, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.layout_armseGlobal.addItem(spacerItem23)
        self.box_armseGlobal = QtGui.QDoubleSpinBox(self.armse)
        self.box_armseGlobal.setObjectName("box_armseGlobal")
        self.layout_armseGlobal.addWidget(self.box_armseGlobal)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_armseGlobal.addItem(spacerItem24)
        self.verticalLayout_6.addLayout(self.layout_armseGlobal)
        self.layout_armseLocal = QtGui.QHBoxLayout()
        self.layout_armseLocal.setObjectName("layout_armseLocal")
        self.label_9 = QtGui.QLabel(self.armse)
        self.label_9.setObjectName("label_9")
        self.layout_armseLocal.addWidget(self.label_9)
        spacerItem25 = QtGui.QSpacerItem(30, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.layout_armseLocal.addItem(spacerItem25)
        self.box_armseLocal = QtGui.QDoubleSpinBox(self.armse)
        self.box_armseLocal.setObjectName("box_armseLocal")
        self.layout_armseLocal.addWidget(self.box_armseLocal)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_armseLocal.addItem(spacerItem26)
        self.verticalLayout_6.addLayout(self.layout_armseLocal)
        self.layout_softMargins = QtGui.QHBoxLayout()
        self.layout_softMargins.setObjectName("layout_softMargins")
        self.check_softMargins = QtGui.QCheckBox(self.armse)
        self.check_softMargins.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check_softMargins.setObjectName("check_softMargins")
        self.layout_softMargins.addWidget(self.check_softMargins)
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_softMargins.addItem(spacerItem27)
        self.verticalLayout_6.addLayout(self.layout_softMargins)
        self.stacked_stopKey.addWidget(self.armse)
        self.verticalLayout_3.addWidget(self.stacked_stopKey)
        self.gridLayout.addWidget(self.group_error, 0, 1, 1, 1)
        self.group_weights = QtGui.QGroupBox(self.centralwidget)
        self.group_weights.setObjectName("group_weights")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.group_weights)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_initWeights = QtGui.QHBoxLayout()
        self.layout_initWeights.setObjectName("layout_initWeights")
        self.label_4 = QtGui.QLabel(self.group_weights)
        self.label_4.setObjectName("label_4")
        self.layout_initWeights.addWidget(self.label_4)
        spacerItem28 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_initWeights.addItem(spacerItem28)
        self.combo_initWeights = QtGui.QComboBox(self.group_weights)
        self.combo_initWeights.setObjectName("combo_initWeights")
        self.combo_initWeights.addItem("")
        self.combo_initWeights.addItem("")
        self.layout_initWeights.addWidget(self.combo_initWeights)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_initWeights.addItem(spacerItem29)
        self.verticalLayout_2.addLayout(self.layout_initWeights)
        self.stacked_initWeights = QtGui.QStackedWidget(self.group_weights)
        self.stacked_initWeights.setObjectName("stacked_initWeights")
        self.random = QtGui.QWidget()
        self.random.setObjectName("random")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.random)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_randomWeights = QtGui.QPushButton(self.random)
        self.button_randomWeights.setFlat(False)
        self.button_randomWeights.setObjectName("button_randomWeights")
        self.horizontalLayout_6.addWidget(self.button_randomWeights)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem30)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        spacerItem31 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem31)
        self.stacked_initWeights.addWidget(self.random)
        self.user = QtGui.QWidget()
        self.user.setObjectName("user")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.user)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.user)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem32 = QtGui.QSpacerItem(34, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem32)
        self.field_weightsFile = QtGui.QLineEdit(self.user)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_weightsFile.sizePolicy().hasHeightForWidth())
        self.field_weightsFile.setSizePolicy(sizePolicy)
        self.field_weightsFile.setObjectName("field_weightsFile")
        self.horizontalLayout_5.addWidget(self.field_weightsFile)
        self.button_weightsFile = QtGui.QToolButton(self.user)
        self.button_weightsFile.setObjectName("button_weightsFile")
        self.horizontalLayout_5.addWidget(self.button_weightsFile)
        spacerItem33 = QtGui.QSpacerItem(27, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem33)
        self.verticalLayout_10.addLayout(self.horizontalLayout_5)
        spacerItem34 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem34)
        self.stacked_initWeights.addWidget(self.user)
        self.verticalLayout_2.addWidget(self.stacked_initWeights)
        spacerItem35 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem35)
        self.gridLayout.addWidget(self.group_weights, 1, 0, 1, 1)
        self.group_control = QtGui.QGroupBox(self.centralwidget)
        self.group_control.setObjectName("group_control")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.group_control)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.layout_control = QtGui.QHBoxLayout()
        self.layout_control.setObjectName("layout_control")
        self.layout_timing = QtGui.QVBoxLayout()
        self.layout_timing.setObjectName("layout_timing")
        self.layout_timeLimit = QtGui.QHBoxLayout()
        self.layout_timeLimit.setObjectName("layout_timeLimit")
        self.check_timeLimit = QtGui.QCheckBox(self.group_control)
        self.check_timeLimit.setObjectName("check_timeLimit")
        self.layout_timeLimit.addWidget(self.check_timeLimit)
        spacerItem36 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_timeLimit.addItem(spacerItem36)
        self.box_timeLimit = QtGui.QTimeEdit(self.group_control)
        self.box_timeLimit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_timeLimit.sizePolicy().hasHeightForWidth())
        self.box_timeLimit.setSizePolicy(sizePolicy)
        self.box_timeLimit.setFrame(True)
        self.box_timeLimit.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.box_timeLimit.setCurrentSection(QtGui.QDateTimeEdit.HourSection)
        self.box_timeLimit.setObjectName("box_timeLimit")
        self.layout_timeLimit.addWidget(self.box_timeLimit)
        self.layout_timing.addLayout(self.layout_timeLimit)
        self.layout_iterLimit = QtGui.QHBoxLayout()
        self.layout_iterLimit.setObjectName("layout_iterLimit")
        self.check_iterLimit = QtGui.QCheckBox(self.group_control)
        self.check_iterLimit.setObjectName("check_iterLimit")
        self.layout_iterLimit.addWidget(self.check_iterLimit)
        spacerItem37 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_iterLimit.addItem(spacerItem37)
        self.box_iterLimit = QtGui.QSpinBox(self.group_control)
        self.box_iterLimit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_iterLimit.sizePolicy().hasHeightForWidth())
        self.box_iterLimit.setSizePolicy(sizePolicy)
        self.box_iterLimit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.box_iterLimit.setMaximum(9999)
        self.box_iterLimit.setObjectName("box_iterLimit")
        self.layout_iterLimit.addWidget(self.box_iterLimit)
        self.layout_timing.addLayout(self.layout_iterLimit)
        self.layout_control.addLayout(self.layout_timing)
        spacerItem38 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.layout_control.addItem(spacerItem38)
        self.layout_miscControl = QtGui.QVBoxLayout()
        self.layout_miscControl.setObjectName("layout_miscControl")
        self.check_useCuda = QtGui.QCheckBox(self.group_control)
        self.check_useCuda.setObjectName("check_useCuda")
        self.layout_miscControl.addWidget(self.check_useCuda)
        self.line = QtGui.QFrame(self.group_control)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layout_miscControl.addWidget(self.line)
        self.check_plotError = QtGui.QCheckBox(self.group_control)
        self.check_plotError.setObjectName("check_plotError")
        self.layout_miscControl.addWidget(self.check_plotError)
        self.check_useConsole = QtGui.QCheckBox(self.group_control)
        self.check_useConsole.setObjectName("check_useConsole")
        self.layout_miscControl.addWidget(self.check_useConsole)
        self.layout_control.addLayout(self.layout_miscControl)
        self.verticalLayout_11.addLayout(self.layout_control)
        self.layout_controlButtons = QtGui.QHBoxLayout()
        self.layout_controlButtons.setObjectName("layout_controlButtons")
        self.button_Learn = QtGui.QPushButton(self.group_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Learn.sizePolicy().hasHeightForWidth())
        self.button_Learn.setSizePolicy(sizePolicy)
        self.button_Learn.setObjectName("button_Learn")
        self.layout_controlButtons.addWidget(self.button_Learn)
        self.button_Test = QtGui.QPushButton(self.group_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Test.sizePolicy().hasHeightForWidth())
        self.button_Test.setSizePolicy(sizePolicy)
        self.button_Test.setObjectName("button_Test")
        self.layout_controlButtons.addWidget(self.button_Test)
        self.button_Export = QtGui.QPushButton(self.group_control)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_Export.sizePolicy().hasHeightForWidth())
        self.button_Export.setSizePolicy(sizePolicy)
        self.button_Export.setObjectName("button_Export")
        self.layout_controlButtons.addWidget(self.button_Export)
        spacerItem39 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_controlButtons.addItem(spacerItem39)
        self.verticalLayout_11.addLayout(self.layout_controlButtons)
        spacerItem40 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem40)
        self.gridLayout.addWidget(self.group_control, 1, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout)
        self.group_Select = QtGui.QGroupBox(self.centralwidget)
        self.group_Select.setObjectName("group_Select")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.group_Select)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.check_lockNet = QtGui.QCheckBox(self.group_Select)
        self.check_lockNet.setObjectName("check_lockNet")
        self.verticalLayout_9.addWidget(self.check_lockNet)
        self.button_Reset = QtGui.QPushButton(self.group_Select)
        self.button_Reset.setObjectName("button_Reset")
        self.verticalLayout_9.addWidget(self.button_Reset)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.scroll_netInstance = QtGui.QScrollArea(self.group_Select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_netInstance.sizePolicy().hasHeightForWidth())
        self.scroll_netInstance.setSizePolicy(sizePolicy)
        self.scroll_netInstance.setMaximumSize(QtCore.QSize(16777215, 50))
        self.scroll_netInstance.setFrameShape(QtGui.QFrame.Panel)
        self.scroll_netInstance.setFrameShadow(QtGui.QFrame.Plain)
        self.scroll_netInstance.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_netInstance.setWidgetResizable(True)
        self.scroll_netInstance.setObjectName("scroll_netInstance")
        self.layout_netInstance = QtGui.QWidget()
        self.layout_netInstance.setGeometry(QtCore.QRect(0, 0, 597, 48))
        self.layout_netInstance.setObjectName("layout_netInstance")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layout_netInstance)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_addNet = QtGui.QToolButton(self.layout_netInstance)
        self.button_addNet.setObjectName("button_addNet")
        self.horizontalLayout.addWidget(self.button_addNet)
        spacerItem41 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem41)
        self.scroll_netInstance.setWidget(self.layout_netInstance)
        self.horizontalLayout_3.addWidget(self.scroll_netInstance)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_12.addWidget(self.group_Select)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1145, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dock_graphPlot = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_graphPlot.sizePolicy().hasHeightForWidth())
        self.dock_graphPlot.setSizePolicy(sizePolicy)
        self.dock_graphPlot.setMinimumSize(QtCore.QSize(400, 286))
        self.dock_graphPlot.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dock_graphPlot.setObjectName("dock_graphPlot")
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graph_plotError = PlotWidget(self.dockWidgetContents_6)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.graph_plotError.setBackgroundBrush(brush)
        self.graph_plotError.setObjectName("graph_plotError")
        self.verticalLayout.addWidget(self.graph_plotError)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_6)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem42 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem42)
        self.box_refreshLimit = QtGui.QSpinBox(self.dockWidgetContents_6)
        self.box_refreshLimit.setFrame(True)
        self.box_refreshLimit.setReadOnly(False)
        self.box_refreshLimit.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.box_refreshLimit.setMinimum(1)
        self.box_refreshLimit.setObjectName("box_refreshLimit")
        self.horizontalLayout_4.addWidget(self.box_refreshLimit)
        spacerItem43 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem43)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_6)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        spacerItem44 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem44)
        self.box_currentIter = QtGui.QSpinBox(self.dockWidgetContents_6)
        self.box_currentIter.setReadOnly(True)
        self.box_currentIter.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.box_currentIter.setMaximum(9999)
        self.box_currentIter.setObjectName("box_currentIter")
        self.horizontalLayout_7.addWidget(self.box_currentIter)
        spacerItem45 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem45)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.check_showThresh = QtGui.QCheckBox(self.dockWidgetContents_6)
        self.check_showThresh.setObjectName("check_showThresh")
        self.gridLayout_2.addWidget(self.check_showThresh, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.dock_graphPlot.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_graphPlot)
        self.dock_graphConsole = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_graphConsole.sizePolicy().hasHeightForWidth())
        self.dock_graphConsole.setSizePolicy(sizePolicy)
        self.dock_graphConsole.setMinimumSize(QtCore.QSize(102, 200))
        self.dock_graphConsole.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dock_graphConsole.setObjectName("dock_graphConsole")
        self.dockWidgetContents_7 = QtGui.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.dockWidgetContents_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graph_console = ConsoleWidget(self.dockWidgetContents_7)
        self.graph_console.setObjectName("graph_console")
        self.horizontalLayout_2.addWidget(self.graph_console)
        self.dock_graphConsole.setWidget(self.dockWidgetContents_7)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dock_graphConsole)
        self.actionImportSamples = QtGui.QAction(MainWindow)
        self.actionImportSamples.setObjectName("actionImportSamples")
        self.actionExportWeights = QtGui.QAction(MainWindow)
        self.actionExportWeights.setObjectName("actionExportWeights")
        self.actionLearn = QtGui.QAction(MainWindow)
        self.actionLearn.setObjectName("actionLearn")
        self.actionTest = QtGui.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionReset_Simulator = QtGui.QAction(MainWindow)
        self.actionReset_Simulator.setObjectName("actionReset_Simulator")
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.action_loadSettings = QtGui.QAction(MainWindow)
        self.action_loadSettings.setObjectName("action_loadSettings")
        self.actionShow_Console = QtGui.QAction(MainWindow)
        self.actionShow_Console.setObjectName("actionShow_Console")
        self.actionShow_Error_Plot = QtGui.QAction(MainWindow)
        self.actionShow_Error_Plot.setObjectName("actionShow_Error_Plot")
        self.actionUse_CUDA = QtGui.QAction(MainWindow)
        self.actionUse_CUDA.setCheckable(True)
        self.actionUse_CUDA.setObjectName("actionUse_CUDA")
        self.menuFile.addAction(self.actionImportSamples)
        self.menuFile.addAction(self.actionExportWeights)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLearn)
        self.menuFile.addAction(self.actionTest)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionReset_Simulator)
        self.menuTools.addAction(self.action_loadSettings)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionUse_CUDA)
        self.menuView.addAction(self.actionShow_Console)
        self.menuView.addAction(self.actionShow_Error_Plot)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.stacked_stopKey.setCurrentIndex(0)
        self.stacked_initWeights.setCurrentIndex(0)
        QtCore.QObject.connect(self.combo_initWeights, QtCore.SIGNAL("currentIndexChanged(int)"), self.stacked_initWeights.setCurrentIndex)
        QtCore.QObject.connect(self.combo_stopKey, QtCore.SIGNAL("currentIndexChanged(int)"), self.stacked_stopKey.setCurrentIndex)
        QtCore.QObject.connect(self.dock_graphConsole, QtCore.SIGNAL("visibilityChanged(bool)"), self.check_useConsole.setChecked)
        QtCore.QObject.connect(self.dock_graphPlot, QtCore.SIGNAL("visibilityChanged(bool)"), self.check_plotError.setChecked)
        QtCore.QObject.connect(self.check_lockNet, QtCore.SIGNAL("toggled(bool)"), self.button_addNet.setDisabled)
        QtCore.QObject.connect(self.check_timeLimit, QtCore.SIGNAL("toggled(bool)"), self.box_timeLimit.setEnabled)
        QtCore.QObject.connect(self.check_iterLimit, QtCore.SIGNAL("toggled(bool)"), self.box_iterLimit.setEnabled)
        QtCore.QObject.connect(self.check_plotError, QtCore.SIGNAL("toggled(bool)"), self.dock_graphPlot.setShown)
        QtCore.QObject.connect(self.check_useConsole, QtCore.SIGNAL("toggled(bool)"), self.dock_graphConsole.setShown)
        QtCore.QObject.connect(self.check_lockNet, QtCore.SIGNAL("toggled(bool)"), self.button_Reset.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.group_io.setTitle(QtGui.QApplication.translate("MainWindow", "Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Import Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.button_importSamples.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Topology", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Sectors", None, QtGui.QApplication.UnicodeUTF8))
        self.check_discreteIn.setText(QtGui.QApplication.translate("MainWindow", "Discrete In", None, QtGui.QApplication.UnicodeUTF8))
        self.check_discreteOut.setText(QtGui.QApplication.translate("MainWindow", "Discrete Out", None, QtGui.QApplication.UnicodeUTF8))
        self.group_error.setTitle(QtGui.QApplication.translate("MainWindow", "Errors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_stopKey.setText(QtGui.QApplication.translate("MainWindow", "Stopping Criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_stopKey.setItemText(0, QtGui.QApplication.translate("MainWindow", "max", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_stopKey.setItemText(1, QtGui.QApplication.translate("MainWindow", "error", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_stopKey.setItemText(2, QtGui.QApplication.translate("MainWindow", "mse", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_stopKey.setItemText(3, QtGui.QApplication.translate("MainWindow", "rmse", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_stopKey.setItemText(4, QtGui.QApplication.translate("MainWindow", "armse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Max Unlearned Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Max Errors Per Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Max % Unlearned Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Max Errors Per Sample", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Global MSE Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Local MSE Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Global RMSE Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Local RMSE Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Global Angular RMSE Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Local Angular RMSE Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.check_softMargins.setText(QtGui.QApplication.translate("MainWindow", "Soft Margins", None, QtGui.QApplication.UnicodeUTF8))
        self.group_weights.setTitle(QtGui.QApplication.translate("MainWindow", "Weights", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Initial Weights", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_initWeights.setItemText(0, QtGui.QApplication.translate("MainWindow", "random", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_initWeights.setItemText(1, QtGui.QApplication.translate("MainWindow", "user", None, QtGui.QApplication.UnicodeUTF8))
        self.button_randomWeights.setText(QtGui.QApplication.translate("MainWindow", "Randomize Weights", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Weights File", None, QtGui.QApplication.UnicodeUTF8))
        self.button_weightsFile.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.group_control.setTitle(QtGui.QApplication.translate("MainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.check_timeLimit.setText(QtGui.QApplication.translate("MainWindow", "Time Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.check_iterLimit.setText(QtGui.QApplication.translate("MainWindow", "Iteration Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.check_useCuda.setText(QtGui.QApplication.translate("MainWindow", "Enable CUDA", None, QtGui.QApplication.UnicodeUTF8))
        self.check_plotError.setText(QtGui.QApplication.translate("MainWindow", "Error Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.check_useConsole.setText(QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.button_Learn.setText(QtGui.QApplication.translate("MainWindow", "Learn", None, QtGui.QApplication.UnicodeUTF8))
        self.button_Test.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.button_Export.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.group_Select.setTitle(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.check_lockNet.setText(QtGui.QApplication.translate("MainWindow", "Lock", None, QtGui.QApplication.UnicodeUTF8))
        self.button_Reset.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.button_addNet.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_graphPlot.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Error Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Iterations Per Update", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Current Iteration", None, QtGui.QApplication.UnicodeUTF8))
        self.check_showThresh.setText(QtGui.QApplication.translate("MainWindow", "Global Limit", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_graphConsole.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportSamples.setText(QtGui.QApplication.translate("MainWindow", "Import Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportWeights.setText(QtGui.QApplication.translate("MainWindow", "Export Weights", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLearn.setText(QtGui.QApplication.translate("MainWindow", "Learn", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset_Simulator.setText(QtGui.QApplication.translate("MainWindow", "Reset Simulator", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.action_loadSettings.setText(QtGui.QApplication.translate("MainWindow", "Import Config. File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Console.setText(QtGui.QApplication.translate("MainWindow", "Show Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Error_Plot.setText(QtGui.QApplication.translate("MainWindow", "Show Error Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUse_CUDA.setText(QtGui.QApplication.translate("MainWindow", "Use CUDA", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph.console import ConsoleWidget
from pyqtgraph import PlotWidget
